### ISSUE TITLE
Long version numbers are cut off

### ISSUE THREAD

**Issue by edwardloveall** [stephendolan/lucky_diff#26]
Thanks for making Lucky Diff! I noticed that long version numbers are cut off. I'm using Firefox Developer Edition 79.0b9 with no zooming.

<img width="138" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/49549/88002099-b0b64e00-cacf-11ea-969e-b476507e4370.png">

**Comment by stephendolan** [comment]
@edwardloveall Unfortunately, I wasn't able to reproduce even with the same version of Firefox 😢 

That said, I took advantage of this issue to refactor that form to use Flexbox instead of static widths and padding/margin. Would you mind loading it up again and seeing if the issue is resolved for you?

For future reference, here's the commit restyling that top form:
https://github.com/stephendolan/lucky_diff/commit/120e63ab91be5a2bf028c1bf03569f78e81dbe64

**Comment by stephendolan** [comment]
I'm going to close this for now, but can re-open if it's still an issue!

**Comment by edwardloveall** [comment]
It is no longer an issue since your redesign. Thanks for fixing 😄
